[build-system]
requires = ["setuptools>=68"]
build-backend = "setuptools.build_meta"

[project]
name = "process-monitor"
version = "1.1.0"
description = "CLI resource monitoring tool"
requires-python = ">=3.9"
dependencies = [
    "psutil"
]

[project.scripts]
monitor = "app.cli:main"
